# -*- coding: utf-8 -*-
"""Mushroom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2COYBCAhxAQVBCW1Ml3Zu_R8ywTsuMA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/mushrooms.csv')

df.head()

df.info()

df.isnull().sum()

X  = df.drop("class", axis=1)
y = df["class"]

X.head()

y

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

col = X.columns

col

